apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart_container
        image: sai2411/flipkart:latest 
        ports:
        - containerPort: 80
